"""Deploy the *interactive* agent to a Hugging Face Gradio Space.

    uv run python scripts/deploy_live_space.py --repo-id nehabharti0802/vichara-live

This is the sibling of deploy_space.py, which publishes the static
recorded-trajectory viewer. Both exist because Hugging Face prices them
differently, and the difference is not the one the pricing page suggests:

    cpu-basic + gradio  ->  402 Payment Required, "requires a PRO subscription"
    zero-a10g  + gradio ->  created, no subscription

The 402 names cpu-basic specifically. ZeroGPU is available to free accounts, so
the live demo runs there. Nothing in this agent touches a GPU -- every model
call goes to the Gemini API -- but ZeroGPU is the tier that will host a Gradio
app for nothing, so that is the tier it uses.

What the Space does NOT get is Node, and therefore not the Pyodide sandbox. A
Gradio Space installs Python requirements and nothing else. That is a supported
degradation rather than a broken deploy: the registry drops `run_python` from
the capability set, the system prompt tells the agent it can no longer execute
code, and the trajectory records the reduced profile. Retrieval, web search and
file tools are unaffected.
"""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
import tomllib
from pathlib import Path

from dotenv import load_dotenv
from huggingface_hub import HfApi

ROOT = Path(__file__).resolve().parents[1]
load_dotenv(dotenv_path=ROOT / ".env")

# Only what serving a query needs. The eval harness, the attack corpus, the
# recorded sweeps and the tests stay out -- they are most of the repository and
# none of them run here.
PAYLOAD = [
    ("src/vichara", "src/vichara"),
    ("config", "config"),
    ("data/fixtures", "data/fixtures"),
]
"""The src/ layout is preserved deliberately, not flattened.

``settings.REPO_ROOT`` is ``Path(__file__).resolve().parents[2]`` -- from
``src/vichara/settings.py`` that is the repository root, and it is how
``config/`` and ``data/fixtures/`` are found. Uploading the package as
``vichara/`` at the Space root would move it one directory up, resolve
REPO_ROOT to the parent of the Space, and fail at runtime looking for a config
directory that is not there.

The alternative was to make REPO_ROOT layout-independent. That is a change to
the module every recorded run loaded, to accommodate a deployment target, and
the deployment target can simply match the layout instead.
"""

SPACE_APP = '''"""Hugging Face Spaces entry point for the live agent.

Generated by scripts/deploy_live_space.py -- edit that, not this.

Three differences from the repository's app.py, each one a deployment that
failed first.

``src`` goes on the import path. A Space installs requirements.txt and does not
install this project, so the package is imported from the filesystem and the
src/ layout has to be made importable by hand.

Everything is built inside ``__main__``, with no module-level ``demo``. That
is not stylistic. The Gradio CLI looks for a module-level ``demo`` and will
launch it itself; with one present *and* a launch here, two servers contend for
7860, the log shows a clean startup and two passing health checks, and the
router then serves 503. The sibling VidyaRAG Space -- same account, same
hardware, running for weeks -- builds inside __main__ for this reason.

``ssr_mode=False``. Gradio's server-side rendering starts a Node process beside
Python, and it is the "Stopping Node.js server..." that ended every earlier
attempt seconds after a clean startup and two successful health checks. This UI
is a textbox and five Markdown panes; SSR buys it nothing and adds a second
runtime that can fail on its own.
"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))

os.environ.setdefault("GRADIO_ANALYTICS_ENABLED", "False")

from vichara.logging import configure_logging  # noqa: E402
from vichara.settings import Settings, load_pipeline_config  # noqa: E402
from vichara.ui.app import build_app  # noqa: E402

# ZeroGPU will not keep a container that never declares GPU work. Without this
# the app starts, answers two health checks, and is then reaped with no
# traceback and no log line -- the router serves 503 while the run log shows a
# clean startup. Nothing here touches a GPU: every model call is an HTTPS
# request to Gemini. The declaration exists because ZeroGPU is the only
# hardware on which Hugging Face hosts a Gradio Space for free.
#
# Guarded, because `spaces` exists only inside a Space and this file is also
# importable locally.
try:
    import spaces  # noqa: E402
except ImportError:  # not running on a Space
    pass
else:

    @spaces.GPU
    def _zerogpu_startup_declaration() -> None:
        """Never invoked. Present only so ZeroGPU will start the container."""

if __name__ == "__main__":
    settings = Settings()
    configure_logging(settings.log_level, settings.log_format)
    build_app(settings, load_pipeline_config(settings.profile)).queue(
        max_size=16
    ).launch(
        server_name="0.0.0.0",
        server_port=7860,
        ssr_mode=False,
    )
'''

# The Space image defaults to a Python older than this project supports, and
# the failure is not obvious from the outside: the build succeeds, then every
# start dies on
#
#     AttributeError: module 'enum' has no attribute 'StrEnum'
#
# StrEnum arrived in 3.11 and is used in settings, tools.config, tools.errors,
# sandbox.base and eval.faults. pyproject already says requires-python
# >=3.11,<3.13; the README frontmatter below is where a Space is told the same
# thing.
SPACE_README = """---
title: Vichara -- live agent
emoji: 🔬
colorFrom: indigo
colorTo: blue
sdk: gradio
sdk_version: 5.50.0
app_file: app.py
pinned: false
license: mit
short_description: Ask it something and watch the trajectory build
---

# Vichara -- the live agent

Ask an anatomy or physiology question and watch the agent work: the stage strip
shows where it is, and the trajectory builds a step at a time underneath.

**What to look at below the answer.** The sources, each traced to something a
tool actually returned. The cost. Any guardrail that fired. And the full
trajectory, with untrusted tool output shown inside its provenance fence rather
than as the agent's own words.

## Three questions worth trying

| ask | what should happen |
| --- | --- |
| How does the hypothalamus control the anterior pituitary gland? | a cited answer |
| Explain the quantum biology chapter in OpenStax Biology | a **refusal** -- there is no such chapter |
| Is it normal? | a **clarifying question**, not a guess |

The refusal is the interesting one. Most agents will invent the chapter.

## What this Space cannot do

**No code execution.** A Gradio Space has no Node runtime, so the Pyodide
sandbox is unavailable and `run_python` is dropped from the capability set. The
agent is told, and says so rather than guessing. Run it locally for the sandbox.

**A shared free-tier quota.** Model calls come from one Gemini free-tier key --
500 requests a day across everyone who visits, at roughly 2-10 per question.
When it runs out the app serves a recorded trajectory with a notice instead of
erroring.

**Fixture retrieval.** 440 real OpenStax passages ranked with BM25, not the
live VidyaRAG service. Same citations, different ranking.

## The numbers

205 runs, 41 hand-annotated tasks, five seeds. Terminal correctness 0.946, tool
precision 1.00, forbidden-tool rate 0.000, refusal correctness 1.00. Prompt
injection: 0.11 baseline, 0.04 hardened.

[Full evaluation and source](https://github.com/NehaBharti08/vichara) ·
[Recorded trajectories](https://huggingface.co/spaces/nehabharti0802/vichara)
"""


def requirements() -> str:
    """Runtime dependencies, read from pyproject rather than duplicated.

    A hand-maintained requirements.txt beside a pyproject is two sources of
    truth that drift silently, and the Space is exactly where that drift
    surfaces as an import error nobody sees until a reviewer clicks the link.
    """
    with (ROOT / "pyproject.toml").open("rb") as handle:
        deps = tomllib.load(handle)["project"]["dependencies"]

    # The Space image installs its own Gradio and will not be argued with:
    #
    #   pip install -r requirements.txt "torch<=2.13.0" \\
    #       gradio[oauth,mcp]==6.27.0 spaces==0.51.3
    #
    # pyproject pins gradio>=5.0,<6.0, so shipping that line leaves the two
    # constraints unsatisfiable and the build dies on a resolver conflict that
    # has nothing to do with this project. Dropping it lets the platform win,
    # which is the only outcome on offer.
    #
    # Safe because the two Gradio 6 breakages this UI had are already fixed:
    # the Blocks `css=` parameter, now a static <style> element, and the
    # gr.HTML `padding` default, now passed explicitly. Both surfaced as
    # deprecation warnings under Gradio 5 and were cleared then.
    deps = [d for d in deps if not d.lower().startswith("gradio")]

    header = (
        "# Generated by scripts/deploy_live_space.py from pyproject.toml.\n"
        "# gradio is deliberately absent: the Space image pins its own version\n"
        "# and a second constraint here only creates a resolver conflict.\n"
    )
    return header + "\n".join(sorted(deps)) + "\n"


def stage(into: Path) -> None:
    for source, target in PAYLOAD:
        src = ROOT / source
        dst = into / target
        dst.parent.mkdir(parents=True, exist_ok=True)
        if src.is_dir():
            shutil.copytree(src, dst, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
        else:
            shutil.copy2(src, dst)
    (into / "app.py").write_text(SPACE_APP, encoding="utf-8")
    (into / "requirements.txt").write_text(requirements(), encoding="utf-8")
    (into / "README.md").write_text(SPACE_README, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-id", required=True)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Stage the payload and list it without uploading.",
    )
    args = parser.parse_args()

    api = HfApi()
    with tempfile.TemporaryDirectory() as tmp:
        staged = Path(tmp)
        stage(staged)

        files = sorted(p.relative_to(staged).as_posix() for p in staged.rglob("*") if p.is_file())
        total = sum(p.stat().st_size for p in staged.rglob("*") if p.is_file())
        print(f"{len(files)} files, {total / 1024:.0f} KB")
        for name in files[:12]:
            print(f"  {name}")
        if len(files) > 12:
            print(f"  ... and {len(files) - 12} more")

        # An allowlist by construction: only PAYLOAD is copied, so a .env or a
        # trajectory log cannot reach a public Space by being in the repo.
        leaked = [f for f in files if f.endswith((".env", ".jsonl.gz")) or "secret" in f.lower()]
        if leaked:
            print(f"refusing to upload, unexpected files: {leaked}", file=sys.stderr)
            return 1

        if args.dry_run:
            print("dry run, nothing uploaded")
            return 0

        api.upload_folder(
            repo_id=args.repo_id,
            repo_type="space",
            folder_path=str(staged),
            commit_message="Deploy the interactive agent",
        )

    print(f"uploaded: https://huggingface.co/spaces/{args.repo_id}")
    print("set GOOGLE_API_KEY in the Space settings, or via add_space_secret, before it will run")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
